# Generated by Django 3.1 on 2020-08-26 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción')),
                ('uploaded', models.DateField(auto_now=True, verbose_name='Fecha de publicación')),
                ('facephoto', models.ImageField(null=True, upload_to='profilephoto', verbose_name='Foto de perfil')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['title', 'uploaded'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('promo', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', related_query_name='price', to='coursesapp.course')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Nombre completo')),
                ('grade', models.CharField(max_length=20, verbose_name='Grado')),
                ('uploaded', models.DateField(auto_now=True, verbose_name='Fecha de publicación')),
                ('facephoto', models.ImageField(null=True, upload_to='profilephoto', verbose_name='Foto de perfil')),
                ('courses', models.ManyToManyField(related_name='instructors', related_query_name='instructor', to='coursesapp.Course')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=50, verbose_name='Estudiante')),
                ('score', models.IntegerField(verbose_name='Puntuación')),
                ('comment', models.CharField(max_length=500, null=True, verbose_name='Comentario')),
                ('uploaded', models.DateField(auto_now=True, verbose_name='Fecha de publicación')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='coursesapp.course')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
