# Generated by Django 3.1 on 2020-08-26 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='coursesapp.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='facephoto',
            field=models.ImageField(blank=True, null=True, upload_to='profilephoto', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='instructors', related_query_name='instructor', to='coursesapp.Course'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='facephoto',
            field=models.ImageField(blank=True, null=True, upload_to='profilephoto', verbose_name='Foto de perfil'),
        ),
    ]
